package com.simple.meditrack

val DEFAULT_IMAGE = listOf(
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_1.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_2.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_3.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_4.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_5.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_6.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_7.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_8.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_9.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_10.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_11.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_12.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_13.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_14.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_15.png",
    "https://raw.githubusercontent.com/hoanganhtuan95ptit/MediTrack/refs/heads/main/res/images/img_reminder_16.png",
)

val DEFAULT_TRANSLATE = mapOf(
    "title_screen_list_alarm" to "Alarms",
    "title_screen_add_alarm" to "Add Alarm",
    "title_screen_update_alarm" to "Update Alarm",
    "title_screen_add_medicine_item" to "Add Medicine",
    "title_screen_update_medicine_item" to "Update Medicine",
    "title_screen_list_medicine" to "Medicines",
    "title_screen_add_medicine" to "Add Medicine",
    "title_screen_update_medicine" to "Update Medicine",

    "title_enter_alarm_time" to "Time (✶)",
    "title_enter_alarm_name" to "Alarm name (✶)",
    "title_enter_alarm_note" to "Note",
    "title_enter_medicine_name" to "Medicine name (✶)",
    "title_enter_medicine_unit" to "Medicine type (✶)",
    "title_enter_medicine_note" to "Note",
    "title_enter_medicine_dosage" to "Dosage (✶)",
    "title_enter_medicine_quantity" to "Quantity (✶)",
    "title_enter_medicine_item" to "Medicine (✶)",
    "title_enter_medicine_item_name" to "Medicine name (✶)",
    "title_enter_medicine_item_unit" to "Medicine type (✶)",
    "title_enter_medicine_item_note" to "Note",
    "title_enter_medicine_item_dosage" to "Dosage (✶)",
    "title_enter_medicine_item_quantity" to "Quantity (✶)",

    "hint_enter_alarm_name" to "Enter alarm name",
    "hint_enter_alarm_note" to "Enter note",
    "hint_enter_medicine_name" to "Enter medicine name",
    "hint_enter_medicine_note" to "Enter note",
    "hint_enter_medicine_quantity" to "Enter medicine quantity",
    "hint_enter_medicine_item_name" to "Enter medicine name",
    "hint_enter_medicine_item_dosage" to "Enter dosage",
    "hint_enter_medicine_item_note" to "Enter note",
    "hint_enter_medicine_item_quantity" to "Enter medicine quantity",

    "action_add_alarm" to "Add alarm",
    "action_update_alarm" to "Update alarm",
    "action_delete_alarm" to "Delete alarm",
    "action_add_medicine" to "Add medicine",
    "action_update_medicine" to "Update medicine",
    "action_delete_medicine" to "Delete medicine",
    "action_add_medicine_item" to "Add medicine",
    "action_update_medicine_item" to "Update medicine",

    "message_please_enter_name_alarm" to "Please enter the alarm name",
    "message_please_add_medicine_item" to "Please add medicine",
    "message_please_enter_medicine_name" to "Please enter the medicine name",
    "message_please_enter_medicine_quantity" to "Please enter the medicine quantity",
    "message_please_enter_medicine_item_name" to "Please enter the medicine name",
    "message_please_enter_medicine_item_dosage" to "Please enter the dosage",
    "message_please_enter_medicine_item_quantity" to "Please enter the medicine quantity",
    "message_receive_notification_medicine" to "Receive notifications when medicine is running low",
    "message_receive_notification_medicine_item" to "Receive notifications when medicine is running low",
    "message_quality_is_out" to "This medicine is out of stock",
    "message_quality_is_only_enough_for_today" to "This medicine is only enough for today",
    "message_quality_is_only_enough_for_x_day" to "This medicine is only enough for \$day day(s)",
    "message_quality_is_enough_for_x_day" to "This medicine is enough for \$day day(s)",
    "message_seen_notification" to "I have seen the alarm",
    "message_please_select_medicine" to "Please select the medicines first",
    "message_took_medicine" to "Took medicine",

    "unit_tablet" to "Tablet",
    "unit_liquid" to "ml",

    "tablet" to "Tablet",
    "liquid" to "Liquid",

    "quality_number" to "\$quality \$unit left",
    "quality_unlimited" to "Unlimited \$unit"
)

